version: "3.6"
services:
  thread-watcher:
    container_name: thread-watcher
    build:
        context: ./bot
        dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./bot/data/data.db
        target: /usr/src/bot/data/data.db
      - type: bind
        source: ./bot/config.json5
        target: /usr/src/bot/config.json5

networks:
  default:
    driver: bridge
