version: "3.6"
services:
  thread-watcher:
    container_name: thread-watcher
    build:
        context: ./bot
        dockerfile: Dockerfile
    restart: always

networks:
  default:
    driver: bridge
