import { mkdir } from 'node:fs/promises';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Leaf {
  parameters: Set<string>;
}

interface Tree {
  children: Record<string, Leaf | Tree>;
}

export function traverse_tree(d: object): Tree {
  const self: Tree = {
    children: {},
  };

  for (const [key, val] of Object.entries(d)) {
    if (typeof val === 'object') {
      self.children[key] = traverse_tree(val);
      continue;
    }
    if (typeof val !== 'string')
      throw new Error(`tree parser reached not with type ${typeof val} where string was expected!`);

    const str_parameters = val
      .matchAll(/{{(?<param>\w+)}}/gm)
      .map((v) => v.groups?.param)
      .filter((param): param is string => !!param);

    self.children[key] = { parameters: new Set(str_parameters) };
  }

  return self;
}

export default async function generate_types(d: object): Promise<void> {
  const tree = traverse_tree(d);
  const lines: string[] = [];
  const argsMap: Record<string, string[]> = {};

  function flatten(node: Tree | Leaf, path: string[] = []) {
    if ('parameters' in node) {
      const fullPath = path.join('.');
      lines.push(`"${fullPath}"`);
      if (node.parameters.size > 0) {
        argsMap[fullPath] = Array.from(node.parameters);
      }
      return;
    }

    for (const [key, child] of Object.entries(node.children)) {
      flatten(child, [...path, key]);
    }
  }

  flatten(tree);

  const file_content = `
// This file is generated by gen_docs.ts 
// -> npm run gen_docs -w bot
export type TKey = ${lines.join(' | ') || 'string'};

export interface TArgs {
${Object.entries(argsMap)
  .map(
    ([key, params]) => `  "${key}": { ${params.map((p) => `${p}: string | number`).join(', ')} };`,
  )
  .join('\n')}
}

export type TFunction = <K extends TKey>(
  key: K, 
  ...args: K extends keyof TArgs ? [options: TArgs[K]] : [options?: any]
) => string;
  `.trim();

  const dir_path = join(process.cwd(), './src/.generated/');

  await mkdir(dir_path, { recursive: true });

  writeFileSync(join(dir_path, 'locales.ts'), file_content);
}
