version: "3.6"
services:
  thread-watcher:
    container_name: thread-watcher
    build:
        context: ./bot
        dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./data/data.db
        target: /data.db

networks:
  default:
    driver: bridge
